### ISSUE TITLE
Allow arrow key for 10 sec forward (  → Right Arrow) or 10 sec rewinds  ( ← Left Arrow) 

### ISSUE THREAD

**Issue by mohitjaisal** [mohitjaisal/VXPlayer#14]
- As we have added the feature for 10 sec forward or 10 rewinds through icons now we have to Allow arrow key for 10 sec forward ( 
→ Right Arrow) or 10-sec rewind ( ← Left Arrow) from the keyboard with javascript

**Comment by mohitjaisal** [comment]
Yeah, Go ahead @mkim219 👍🏻

**Comment by ksherm337** [comment]
@mkim219 I am interested in seeing your solution when you're done. I forked it and got it working myself, but I'm still a total noob so I'm not sure how "clean" it is.

**Comment by mkim219** [comment]
Hi @mohitjaisal, Can you take a look PR?

**Comment by mkim219** [comment]
@mohitjaisal I have committed the space bar feature. Please review and confirm.

**Comment by mohitjaisal** [comment]
good work @mkim219 👍🏻
