### ISSUE TITLE
Logo set with media player

### ISSUE THREAD

**Issue by mohitjaisal** [mohitjaisal/VXPlayer#4]
- Set the VX Player logo in media player skin
**Note:** _VX Player logo is in assets folder_

**Comment by sharonibose** [comment]
@mohitjaisal, could you kindly assign me this task?

**Comment by mohitjaisal** [comment]
Go ahead @sharonibose 👍🏻 , Make sure the logo size satisfy the media player skin✌

**Comment by mohitjaisal** [comment]
@sharonibose are you still working on this?
